#lang racket
(require rackunit racket/file racket/runtime-path racket/system racket/unix-socket)
(define-runtime-path root "../..")
(module+ test
  (define scratch (make-temporary-file "m8-2-source-test-~a" 'directory))
  (define clone (build-path scratch "repository"))
  (define output (build-path scratch "snapshot"))
  (define git (find-executable-path "git"))
  (define (git-text . arguments)
    (define out (open-output-string))
    (parameterize ([current-output-port out])
      (unless (apply system* git "-C" root arguments) (error 'source-test "Git fixture inventory failed")))
    (string-trim (get-output-string out)))
  (define git-dir (git-text "rev-parse" "--absolute-git-dir"))
  (define index (build-path root (git-text "rev-parse" "--git-path" "index")))
  (define initial-index (file->bytes index))
  (define listener #f)
  (define (write-file relative bytes)
    (define path (build-path clone relative))
    (make-parent-directory* path)
    (call-with-output-file path (lambda (out) (write-bytes bytes out)) #:exists 'truncate))
  (dynamic-wind void
    (lambda ()
      (make-directory clone)
      ;; A temporary worktree view of the existing read-only Git inventory.
      ;; No init/add/commit or index write is needed to construct this fixture.
      (write-file ".git" (string->bytes/utf-8 (format "gitdir: ~a\n" git-dir)))
      (copy-file (build-path root ".gitignore") (build-path clone ".gitignore"))
      (write-file "README.md" #"changed tracked source\n")
      (for ([path '("new-source.rkt" "new-source.rs" "new-source.md")]) (write-file path #"legitimate nonignored source\n"))
      (for ([path '(".local/acceptance/m8-2/log" ".local/acceptance/m8-2/test.db" ".local/acceptance/m8-2/secret.fixture"
                    "flutter/apps/pos_terminal/build/ignored-output")]) (write-file path #"intentionally fake ignored state\n"))
      (set! listener (unix-socket-listen (build-path clone ".local/probe.sock")))
      (test-case "snapshot preserves current tracked/new source and excludes ignored local state/socket"
        (check-true (system* (find-executable-path "racket") (build-path root "scripts/acceptance/nix-source-snapshot.rkt") clone output))
        (check-equal? (file->bytes (build-path output "README.md")) #"changed tracked source\n")
        (for ([path '("new-source.rkt" "new-source.rs" "new-source.md")])
          (check-equal? (file->bytes (build-path output path)) #"legitimate nonignored source\n"))
        (check-false (directory-exists? (build-path output ".local")))
        (check-false (directory-exists? (build-path output "flutter/apps/pos_terminal/build")))
        (check-false (file-exists? (build-path output ".git")))
        (check-equal? (file->bytes index) initial-index)))
    (lambda ()
      (when listener (unix-socket-close-listener listener))
      (delete-directory/files scratch))))
